### ISSUE TITLE
remove grib2grib (was: questions about grib2grib - can it be removed from grib_util?)

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-grib_util#114]
In grib2grib.f we have:

```
Finds and extracts grib records from a grib file made
by gribawp1 for family of services.
```

What is gribawp1?

What is "family of services"?

Is this utility still needed? If so, what applications or users are using it?

**Comment by edwardhartnett** [comment]
@BoiVuong-NOAA

**Comment by BoiVuong-NOAA** [comment]
This program is for AWIPS in GRIB1.  I think it is no longer use in production.  We can remove it out of module grib_util in next release.

**Comment by edwardhartnett** [comment]
OK, who was the user who originally requested this? Can we get them to confirm grib2grib is no longer needed?

**Comment by BoiVuong-NOAA** [comment]
I think the users are WFOs (AWIPS).  This code was written in 1998.  I 
do know who can confirm grib2grib2 is no longer needed. You can check 
with NCO.

**Comment by edwardhartnett** [comment]
OK, we have checked with NCO, and it has been announced that we are removing grib2grib before the next release of NCEPLIBS-grib_util. I will remove it...

**Comment by BoiVuong-NOAA** [comment]
Thanks Ed.
