### ISSUE TITLE
add more tests

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-grib_util#116]
We have a basic set of tests running, but we need to fill in the gaps...

**Comment by AlexanderRichert-NOAA** [comment]
Adding to this: ip used to have reg tests that ran its own copy of copygb with a bunch of different grid configurations. Let's add more grid configs to run_copygb_tests.sh to more robustly check that ip & sp are behaving correctly.

**Comment by edwardhartnett** [comment]
Many tests have been added! I will close this issue, and we will continue to add more tests under future issues.
