### ISSUE TITLE
GRIB1 utils still needed anywhere?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-grib_util#122]
There are a number of GRIB1 utilities in grib_util. Are they used any more? I thought we had no more GRIB1 processing...

* copygb
* grbindex
* tocgrib
* wgrib

I have asked @BoiVuong-NOAA if he knows of any uses of these utilities in processing.

**Comment by BoiVuong-NOAA** [comment]
Yes, They are still using those utilities in FAA and AWIPS (CONUS grid id 211).  We should keep them for awhile.
Thanks,
Boi

**Comment by edwardhartnett** [comment]
OK, they are using all 4 of the utilities?

**Comment by BoiVuong-NOAA** [comment]
I am not sure about copygb and tocgrib.  But, Users still use wgrib for displaying content of GRIB1 and grbindex in AWIPS.
We can ask NCO for copygb and tocgrib.

**Comment by edwardhartnett** [comment]
These are used in UFS_UTILS in iceblend and others. @GeorgeGayno-NOAA do you know if UFS_UTILS needs to keep using GRIB1 utilities?

**Comment by GeorgeGayno-NOAA** [comment]
> These are used in UFS_UTILS in iceblend and others. @GeorgeGayno-NOAA do you know if UFS_UTILS needs to keep using GRIB1 utilities?

copygb is still used by UFS_UTILS. And I would bet most of them are still used in operations.

**Comment by GlennCreighton** [comment]
Not that you guys need to worry about us, but we in the USAF 557WW still use copygb and wgrib, fwiw.  We are going to be pulling your NCEPLIBS-grib_util code into our pipelines shortly (we may or may not still be running ancient code once found on NCEP's old ftp sites).

**Comment by edwardhartnett** [comment]
OK so we still don't know of anyone using tocgrib?

@BoiVuong-NOAA do you know who that was written for?

From the code:

```
!> Program reads selected GRIB fields from a file, adds a TOC Flag Field
!> separator block and WMO Header in front of each GRIB field, and
!> writes them out to a new file. The output file is in the format
!> required for TOC's FTP Input Service, which can be used to
!> disseminate the GRIB bulletins. This service is described at
!> http://weather.gov/tg/ftpingest.html.
!>
!> ### Program History Log
!> Date | Programmer | Comments
!> -----|------------|---------
!> 2003-03-28 | Gilbert | Initial
!> 2012-10-22 | Vuong | changed variable envvar to character*6
!> 2016-10-15 | Vuong | increased length of file name to 200 characters

```

**Comment by BoiVuong-NOAA** [comment]
This tocgrib uses to insert WMO header in grib1 for AWIPS.  We can check 
with NCO to confirm before we can remove it from grib_util.

**Comment by edwardhartnett** [comment]
What about tocgrib2 and tcgrib2super? Are they still used?

I will ask NCO about tocgrib...

**Comment by BoiVuong-NOAA** [comment]
Yes, These two codes (tocgrib2 and tocgrib2super)  are using in PROD.

**Comment by edwardhartnett** [comment]
What is PROD?

**Comment by BoiVuong-NOAA** [comment]
PROD is production.

**Comment by edwardhartnett** [comment]
So you mean the GFS? Or something else? Please be as specific as possible...

**Comment by BoiVuong-NOAA** [comment]
These codes are using in all models (GFS, NAM, SMOKE, RAP, HRRR, NWPS, 
etc.) in production for AWIPS  and NDFD.

**Comment by edwardhartnett** [comment]
From Steve Earle:

> I know tocgrib is still used. I'm not sure how widespread its use is but I know at least the RAP uses it to generate products for the FAA.
> I suspect there are others who still use it for grib1 products that the FAA can't seem to get off of...
> Steven

**Comment by edwardhartnett** [comment]
OK, so who do I list as users for:
* cnvgrib
* copygb2
* degrib2
* grb2index

@BoiVuong-NOAA do you know where these are being used?

**Comment by BoiVuong-NOAA** [comment]
These codes are available to all users who want to convert from grib2 to grib1 (cnvgrib) or to interpolate (copygb2) or to see content of grib2 file (degrib2) or to generate an grib2 index file (grb2index).   I do not know where are being used in production. You might check with NCO.
