### ISSUE TITLE
make[1]: *** [CMakeFiles/Makefile2:1101: src/copygb2/CMakeFiles/copygb2.dir/all] Error 2

### ISSUE THREAD

**Issue by hastiin-manuelito** [NOAA-EMC/NCEPLIBS-grib_util#137]
First, a forewarning, I am not savvy on the technical verbiage, so please bare that in mind. 

I received this error when trying to 'make' the NCEPLIBS-grib_util package.

Here is the content of the output:

[  2%] Linking Fortran executable copygb
[ 13%] Built target grb2index
[ 36%] Linking Fortran executable copygb2
[ 47%] Built target cnvgrib
[ 55%] Building Fortran object src/grbindex/CMakeFiles/grbindex.dir/grbindex.f.o
[ 61%] Built target degrib2
[ 63%] Building Fortran object src/tocgrib/CMakeFiles/tocgrib.dir/makwmo.F90.o
/usr/bin/ld: CMakeFiles/copygb.dir/copygb.F90.o: in function `intgrib1_':
/home/derrick/makes/NCEPLIBS-grib_util/src/copygb/copygb.F90:1222: undefined reference to `ipolates_'
/usr/bin/ld: /home/derrick/makes/NCEPLIBS-grib_util/src/copygb/copygb.F90:1297: undefined reference to `>
/usr/bin/ld: /home/derrick/makes/NCEPLIBS-grib_util/src/copygb/copygb.F90:1328: undefined reference to `>
/usr/bin/ld: /home/derrick/makes/NCEPLIBS-grib_util/src/copygb/copygb.F90:1287: undefined reference to `>
/usr/bin/ld: /home/derrick/makes/NCEPLIBS-grib_util/src/copygb/copygb.F90:1228: undefined reference to `>
/usr/bin/ld: /home/derrick/makes/NCEPLIBS-grib_util/src/copygb/copygb.F90:1265: undefined reference to `>
/usr/bin/ld: /home/derrick/makes/NCEPLIBS-grib_util/src/copygb/copygb.F90:1250: undefined reference to `>
/usr/bin/ld: /home/derrick/makes/NCEPLIBS-grib_util/src/copygb/copygb.F90:1209: undefined reference to `>
/usr/bin/ld: CMakeFiles/copygb2.dir/copygb2.F90.o: in function `intgrib2.3.constprop.0':
/home/derrick/makes/NCEPLIBS-grib_util/src/copygb2/copygb2.F90:1432: undefined reference to `ipolatev_'
/usr/bin/ld: CMakeFiles/copygb2.dir/copygb2.F90.o: in function `intgrib1':
/home/derrick/makes/NCEPLIBS-grib_util/src/copygb2/copygb2.F90:1380: undefined reference to `ipolates_'
/usr/bin/ld: /home/derrick/makes/NCEPLIBS-grib_util/src/copygb2/copygb2.F90:1362: undefined reference to>
/usr/bin/ld: /home/derrick/makes/NCEPLIBS-grib_util/src/copygb2/copygb2.F90:1368: undefined reference to>
/usr/bin/ld: /home/derrick/makes/NCEPLIBS-grib_util/src/copygb2/copygb2.F90:1405: undefined reference to>
/usr/bin/ld: /home/derrick/makes/NCEPLIBS-grib_util/src/copygb2/copygb2.F90:1415: undefined reference to>
/usr/bin/ld: /home/derrick/makes/NCEPLIBS-grib_util/src/copygb2/copygb2.F90:1354: undefined reference to>
/usr/bin/ld: /home/derrick/makes/NCEPLIBS-grib_util/src/copygb2/copygb2.F90:1390: undefined reference to>
collect2: error: ld returned 1 exit status
make[2]: *** [src/copygb/CMakeFiles/copygb.dir/build.make:101: src/copygb/copygb] Error 1
make[1]: *** [CMakeFiles/Makefile2:1075: src/copygb/CMakeFiles/copygb.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 66%] Building Fortran object src/tocgrib/CMakeFiles/tocgrib.dir/mkfldsep.F90.o
collect2: error: ld returned 1 exit status
make[2]: *** [src/copygb2/CMakeFiles/copygb2.dir/build.make:110: src/copygb2/copygb2] Error 1
make[1]: *** [CMakeFiles/Makefile2:1101: src/copygb2/CMakeFiles/copygb2.dir/all] Error 2
[ 69%] Building Fortran object src/tocgrib/CMakeFiles/tocgrib.dir/tocgrib.F90.o
[ 72%] Linking Fortran executable grbindex
[ 72%] Built target grbindex
[ 75%] Linking Fortran executable tocgrib
[ 75%] Built target tocgrib
make: *** [Makefile:146: all] Error 2`

I assume there may be something wrong with my directory structure, however, when using cmake I did not receive any errors or warnings. I am fairly new to the build process (in general), so some direction is appreciated.

My directory w/relevant folders and files:
$HOME/makes/NCEPLIBS-bacio
$HOME/makes/NCEPLIBS-g2
$HOME/makes/NCEPLIBS-grib_utils
$HOME/makes/NCEPLIBS-ip
$HOME/makes/NCEPLIBS-sp
$HOME/makes/NCEPLIBS-w3emc
$HOME/makes/master-ncep 

I did:
`cmake -DCMAKE_INSTALL_PREFIX=/home/derrick/makes/master-ncep /home/derrick/makes/NCEPLIBS-*`
for all but NCEPLIBS-grib_utils, no errors or warnings output here.

And for NCEPLIBS-grib_utils I did:
`cmake -DCMAKE_INSTALL_PREFIX=/home/derrick/makes/master-ncep -DCMAKE_PREFIX_PATH=/home/derrick/makes/master-ncep`

All other relevant dependencies for NCEPLIBS-grib_utils are in their "default" locations as configured for my system, Arch.

I don't know if this is relevant but here is the output for "lscpu":

[lscpuout.txt](https://github.com/NOAA-EMC/NCEPLIBS-grib_util/files/8126292/lscpuout.txt)

**Comment by kgerheiser** [comment]
Can you show the CMake output right at the beginning when it finds the packages, especially NCEPLIBS-ip?

**Comment by hastiin-manuelito** [comment]
Here it is.

CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.


-- Found bacio: $HOME/makes/master-ncep/lib/libbacio.a (found version "2.5.0")
-- Found sp: $HOME/makes/master-ncep/lib/libsp_4.a (found version "2.3.3")
-- Found sp: $HOME/makes/master-ncep/lib/libsp_4.a (found version "2.3.3")
-- Found ip: $HOME/makes/master-ncep/lib/libip_4.a (found version "4.0.0")
-- Found bacio: $HOME/makes/master-ncep/lib/libbacio.a (found version "2.5.0")
-- Found w3emc: $HOME/makes/master-ncep/lib/libw3emc_4.a (found version "2.9.2")
-- Found bacio: $HOME/makes/master-ncep/lib/libbacio.a (found version "2.5.0")
-- Found g2: $HOME/makes/master-ncep/lib/libg2_4.a (found version "3.4.5")
-- Using bacio library bacio
-- In cnvgrib using bacio library bacio
-- In cnvgrib /usr/lib/libjasper.so;/usr/lib/libjpeg.so
-- In cnvgrib /usr/lib/libz.so
-- Configuring done
-- Generating done
-- Build files have been written to: $HOME/makes/NCEPLIBS-grib_util

**Comment by kgerheiser** [comment]
Try building NCEPLIBS-ip v3.3.3. 

v4.0.0 has some major changes that are not integrated with this repo yet.

**Comment by hastiin-manuelito** [comment]
Did that and it worked! Awesome! Thanks for your assistance!
