### ISSUE TITLE
Compile failure using latest LLVM based OneAPI fortran compiler (ifx)

### ISSUE THREAD

**Issue by dkokron** [NOAA-EMC/NCEPLIBS-grib_util#206]
/opt/intel/oneapi/compiler/2023.1.0/linux/bin/ifx  -isystem /home/dkokron/opt/intelLLVM-2023.1.0/g2/3.4.5/include_d -isystem /home/dkokron/opt/intelLLVM-2023.1.0/libpng/1.6.35/include -isystem /home/dkokron/opt/intelLLVM-2023.1.0/zlib/1.2.11/include -isystem /home/dkokron/opt/intelLLVM-2023.1.0/bacio/2.4.1/include_4 -isystem /home/dkokron/opt/intelLLVM-2023.1.0/w3emc/2.9.2/include_d -isystem /home/dkokron/opt/intelLLVM-2023.1.0/ip/3.3.3/include_d -isystem /home/dkokron/opt/intelLLVM-2023.1.0/sp/2.3.3/include_d -g -r8 -auto -convert big_endian -fpp -fPIC -w -O3 -g -r8 -auto -convert big_endian -fpp -fPIC -w -fiopenmp -c /home/dkokron/Projects/NCEP/UFS/hpc-stack/pkg/grib_util-v1.2.4/src/copygb2/copygb2.F90 -o CMakeFiles/copygb2.dir/copygb2.F90.o

/home/dkokron/Projects/NCEP/UFS/hpc-stack/pkg/grib_util-v1.2.4/src/copygb2/copygb2.F90(956): error #6633: The type of the actual argument differs from the type of the dummy argument.   [FLD]
            GFLD1%FLD,GFLDV%FLD,IGDTN,KGDTI,MI, &
------------------^
/home/dkokron/Projects/NCEP/UFS/hpc-stack/pkg/grib_util-v1.2.4/src/copygb2/copygb2.F90(956): error #6633: The type of the actual argument differs from the type of the dummy argument.   [FLD]
            GFLD1%FLD,GFLDV%FLD,IGDTN,KGDTI,MI, &
----------------------------^
/home/dkokron/Projects/NCEP/UFS/hpc-stack/pkg/grib_util-v1.2.4/src/copygb2/copygb2.F90(1110): error #6633: The type of the actual argument differs from the type of the dummy argument.   [FLD]
                  KM,IBM,GFLDM%BMAP,GFLDM%FLD,GFLDMV%FLD, &
------------------------------------------^
/home/dkokron/Projects/NCEP/UFS/hpc-stack/pkg/grib_util-v1.2.4/src/copygb2/copygb2.F90(1110): error #6633: The type of the actual argument differs from the type of the dummy argument.   [FLD]
                  KM,IBM,GFLDM%BMAP,GFLDM%FLD,GFLDMV%FLD, &
-----------------------------------------------------^
/home/dkokron/Projects/NCEP/UFS/hpc-stack/pkg/grib_util-v1.2.4/src/copygb2/copygb2.F90(1167): error #6795: The target must be of the same type and kind type parameters as the pointer.   [FLD]
       GFLD1%FLD => F1I
-------------^
/home/dkokron/Projects/NCEP/UFS/hpc-stack/pkg/grib_util-v1.2.4/src/copygb2/copygb2.F90(1174): error #6795: The target must be of the same type and kind type parameters as the pointer.   [FLD]
          GFLD1%FLD => G1I
----------------^
/home/dkokron/Projects/NCEP/UFS/hpc-stack/pkg/grib_util-v1.2.4/src/copygb2/copygb2.F90(1204): error #6106: Not a valid argument for ASSOCIATE or SELECT TYPE.   [ASSOCIATED]
    IF (ASSOCIATED(GFLD1%FLD,G1I)) then
-------------------^

**Comment by edwardhartnett** [comment]
Yes.

This is old old code. I don't know how to fix this, do you?

**Comment by dkokron** [comment]
Ed,
I'll need to investigate further.  Might have something to do with
C/Fortran interoperability.
Dan

**Comment by edwardhartnett** [comment]
OK, we just added support for OneAPI compiler, and it's tested on the CI. This is also now supported in the g2 library.

Reopen this issue or open a new one if this doesn't work for you.
