### ISSUE TITLE
Despite all pre-requisites code - compilation not successful

### ISSUE THREAD

**Issue by stephentjemkes** [NOAA-EMC/NCEPLIBS-grib_util#207]
Hi,
I just installed all prerequisites including latest jasper (4.0.0) but the build failed.
log of the cmake command is enclosed
any recommendation?
could there be a conflict with ecmwf eccodes?
thanks
stephen

muppet) stephen@stephen-Inspiron-16-7610:~/local/NCEPLIBS-grib_util/build$ cmake -DCMAKE_INSTALL_PREFIX=/home/stephen/local -DCMAKE_PREFIX_PATH=/home/stephen/local/ ..
-- The C compiler identification is GNU 11.3.0
-- The Fortran compiler identification is GNU 11.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Check for working Fortran compiler: /bin/gfortran - skipped
-- Setting build type to 'Release' as none was specified.
-- Found JPEG: /usr/lib/x86_64-linux-gnu/libjpeg.so (found version "80") 
-- Found Jasper: /home/stephen/local/lib/libjasper.so (found suitable version "4.0.0", minimum required is "2.0.25") 
-- Found ZLIB: /home/stephen/local/lib/libz.so (found version "1.2.11") 
-- Found PNG: /home/stephen/local/lib/libpng.a (found version "1.6.36") 
-- Found bacio: /home/stephen/local/lib/libbacio.a (found version "2.6.0")
-- Found sp: /home/stephen/local/lib/libsp_4.a (found version "2.4.0")
-- Found sp: /home/stephen/local/lib/libsp_4.a (found version "2.4.0")
-- Found ip: /home/stephen/local/lib/libip_4.a (found version "4.0.0")
-- Found bacio: /home/stephen/local/lib/libbacio.a (found version "2.6.0")
-- Found bufr: /home/stephen/local/lib/libbufr_4.a (found version "11.7.1")
-- Found w3emc: /home/stephen/local/lib/libw3emc_4.a (found version "2.10.0")
-- Found bacio: /home/stephen/local/lib/libbacio.a (found version "2.6.0")
-- Found bacio: /home/stephen/local/lib/libbacio.a (found version "2.6.0")
-- Found bufr: /home/stephen/local/lib/libbufr_4.a (found version "11.7.1")
-- Found w3emc: /home/stephen/local/lib/libw3emc_4.a (found version "2.10.0")
-- Found g2: /home/stephen/local/lib/libg2_4.a (found version "3.5.0")
-- g2c_compare found: /home/stephen/local/bin/g2c_compare
-- Using bacio library bacio
-- In cnvgrib using bacio library bacio
-- In cnvgrib /home/stephen/local/lib/libjasper.so;/usr/lib/x86_64-linux-gnu/libjpeg.so
-- In cnvgrib /home/stephen/local/lib/libz.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/stephen/local/NCEPLIBS-grib_util/build
(muppet) stephen@stephen-Inspiron-16-7610:~/local/NCEPLIBS-grib_util/build$ make -j4
Scanning dependencies of target copygb
Scanning dependencies of target copygb2
Scanning dependencies of target cnvgrib
Scanning dependencies of target grb2index
[  2%] Building Fortran object src/grb2index/CMakeFiles/grb2index.dir/grb2index.F90.o
[  5%] Building Fortran object src/copygb/CMakeFiles/copygb.dir/copygb.F90.o
[  7%] Building Fortran object src/copygb2/CMakeFiles/copygb2.dir/copygb2.F90.o
[ 10%] Building Fortran object src/cnvgrib/CMakeFiles/cnvgrib.dir/cnv12.F90.o
[ 12%] Linking Fortran executable grb2index
[ 12%] Built target grb2index
Scanning dependencies of target degrib2
[ 15%] Building Fortran object src/degrib2/CMakeFiles/degrib2.dir/degrib2.F90.o
[ 17%] Building Fortran object src/cnvgrib/CMakeFiles/cnvgrib.dir/cnv22.F90.o
[ 20%] Building Fortran object src/degrib2/CMakeFiles/degrib2.dir/prlevel.F90.o
[ 22%] Building Fortran object src/degrib2/CMakeFiles/degrib2.dir/prvtime.F90.o
[ 25%] Building Fortran object src/cnvgrib/CMakeFiles/cnvgrib.dir/gds2gdt.F90.o
[ 27%] Linking Fortran executable copygb
[ 30%] Linking Fortran executable degrib2
/bin/ld: CMakeFiles/copygb.dir/copygb.F90.o: in function `intgrib1_':
/home/stephen/local/NCEPLIBS-grib_util/src/copygb/copygb.F90:1218: undefined reference to `ipolates_'
/bin/ld: /home/stephen/local/NCEPLIBS-grib_util/src/copygb/copygb.F90:1293: undefined reference to `ipolatev_'
/bin/ld: /home/stephen/local/NCEPLIBS-grib_util/src/copygb/copygb.F90:1324: undefined reference to `ipolatev_'
/bin/ld: /home/stephen/local/NCEPLIBS-grib_util/src/copygb/copygb.F90:1283: undefined reference to `ipolatev_'
/bin/ld: /home/stephen/local/NCEPLIBS-grib_util/src/copygb/copygb.F90:1224: undefined reference to `ipolates_'
/bin/ld: /home/stephen/local/NCEPLIBS-grib_util/src/copygb/copygb.F90:1261: undefined reference to `ipolatev_'
/bin/ld: /home/stephen/local/NCEPLIBS-grib_util/src/copygb/copygb.F90:1246: undefined reference to `ipolates_'
/bin/ld: /home/stephen/local/NCEPLIBS-grib_util/src/copygb/copygb.F90:1205: undefined reference to `ipolates_'
collect2: error: ld returned 1 exit status
make[2]: *** [src/copygb/CMakeFiles/copygb.dir/build.make:102: src/copygb/copygb] Error 1
make[1]: *** [CMakeFiles/Makefile2:1075: src/copygb/CMakeFiles/copygb.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 35%] Building Fortran object src/cnvgrib/CMakeFiles/cnvgrib.dir/pds2pdtens.F90.o
[ 35%] Building Fortran object src/cnvgrib/CMakeFiles/cnvgrib.dir/makepdsens.F90.o
[ 37%] Building Fortran object src/cnvgrib/CMakeFiles/cnvgrib.dir/putgbexn.F90.o
[ 37%] Built target degrib2
[ 40%] Building Fortran object src/cnvgrib/CMakeFiles/cnvgrib.dir/cnv21.F90.o
[ 42%] Building Fortran object src/cnvgrib/CMakeFiles/cnvgrib.dir/cnvgrib.F90.o
[ 45%] Building Fortran object src/cnvgrib/CMakeFiles/cnvgrib.dir/gdt2gds.F90.o
[ 47%] Building Fortran object src/cnvgrib/CMakeFiles/cnvgrib.dir/makepds.F90.o
[ 50%] Building Fortran object src/cnvgrib/CMakeFiles/cnvgrib.dir/pds2pdt.F90.o
[ 52%] Building Fortran object src/cnvgrib/CMakeFiles/cnvgrib.dir/setbit.F90.o
[ 55%] Linking Fortran executable cnvgrib
[ 55%] Built target cnvgrib
[ 57%] Linking Fortran executable copygb2
/bin/ld: CMakeFiles/copygb2.dir/copygb2.F90.o: in function `intgrib2.3.constprop.0':
/home/stephen/local/NCEPLIBS-grib_util/src/copygb2/copygb2.F90:1442: undefined reference to `ipolatev_'
/bin/ld: CMakeFiles/copygb2.dir/copygb2.F90.o: in function `intgrib1':
/home/stephen/local/NCEPLIBS-grib_util/src/copygb2/copygb2.F90:1390: undefined reference to `ipolates_'
/bin/ld: /home/stephen/local/NCEPLIBS-grib_util/src/copygb2/copygb2.F90:1372: undefined reference to `ipolates_'
/bin/ld: /home/stephen/local/NCEPLIBS-grib_util/src/copygb2/copygb2.F90:1378: undefined reference to `ipolates_'
/bin/ld: /home/stephen/local/NCEPLIBS-grib_util/src/copygb2/copygb2.F90:1415: undefined reference to `ipolatev_'
/bin/ld: /home/stephen/local/NCEPLIBS-grib_util/src/copygb2/copygb2.F90:1425: undefined reference to `ipolatev_'
/bin/ld: /home/stephen/local/NCEPLIBS-grib_util/src/copygb2/copygb2.F90:1364: undefined reference to `ipolates_'
/bin/ld: /home/stephen/local/NCEPLIBS-grib_util/src/copygb2/copygb2.F90:1400: undefined reference to `ipolatev_'
collect2: error: ld returned 1 exit status
make[2]: *** [src/copygb2/CMakeFiles/copygb2.dir/build.make:112: src/copygb2/copygb2] Error 1
make[1]: *** [CMakeFiles/Makefile2:1101: src/copygb2/CMakeFiles/copygb2.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

**Comment by edwardhartnett** [comment]
What version of NCEPLIBS-ip did you use? You should be using 3.3.3.

**Comment by edwardhartnett** [comment]
I'm about to do a release, and it builds well with the most recent versions of sp, ip, jasper, and g2.

The github actions CI system shows how to build on a variety of platforms, take a look at the files in the .github/workflows subdirecotry to see how the CI builds everything.

Please let me know if you still have problems.

**Comment by stephentjemkes** [comment]
Will do. Thank you for the effort

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
