### ISSUE TITLE
Release version 1.3.0

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-grib_util#250]
We need to release a new version to go with the new g2 release, which fixes several problems.

**Comment by AlexanderRichert-NOAA** [comment]
@edwardhartnett do we have an ETA for this release? If we can get it out in the next couple weeks then I'll plan to update default ip, w3emc, and grib_util versions in spack-stack in one go.

**Comment by edwardhartnett** [comment]
Yes we can do it when we need it. So sometime in the next couple of weeks for sure.
