### ISSUE TITLE
'stop' with variable fails with intel 19

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [NOAA-EMC/NCEPLIBS-grib_util#322]
As is, grib-util 1.4.0 fails to build on Acorn with Intel 19 because of the `stop iret` statements in src/grb2index/grb2index.F90. Error message: "Either a PAUSE, STOP or ERROR STOP statement has an invalid argument"

**Comment by AlexanderRichert-NOAA** [comment]
Looks like it's in the F2018 standards... https://www.intel.com/content/www/us/en/developer/articles/technical/fortran-compiler-support-for-fortran-language-standards.html

**Comment by edwardhartnett** [comment]
Is this compiler different from the intel compilers we use in CI?

**Comment by AlexanderRichert-NOAA** [comment]
Yes, it's older- looking at the documentation for that version specifically, it seems to have some F2018 features but not that particular one.

**Comment by edwardhartnett** [comment]
Is acorn behind the other machines for intel compilers?

Can we test with that version of the compiler in the CI?

**Comment by AlexanderRichert-NOAA** [comment]
Yes, Acorn is unusual on account of reflecting the operational machines where pretty much everything uses Intel 19. 

Unfortunately that version of Intel isn't publicly available, so I don't think there's any straightforward way to test it in the CI...

Thankfully this was easy to patch on Acorn in the current spack-stack release, so I don't think this will be urgently needed in a release since as far as I can tell all of our other HPC systems use more recent Intel versions.

**Comment by edwardhartnett** [comment]
This has been fixed in the code. They have been changed to "stop 9"
