### ISSUE TITLE
need some tests for tocgrib2

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-grib_util#324]
We have none.

**Comment by HuiyaChuang-NOAA** [comment]
from @hsinmulin-NOAA 
Hi, Ed

I have a sample backup in HPSS and you can download it to any workstation (WOSCC2, HERA..)
It is
/NCEPDEV/emc-meso/5year/Hsin-Mu.Lin/tmp/xxx-na3km.tar

Every necessary files are ready there, just run "tocgrib2_awips.sh"

Also available on HERA
/scratch2/NCEPDEV/stmp3/Hsin-Mu.Lin/xxx-na3km

Sincerely,

Lin

**Comment by edwardhartnett** [comment]
@AlexanderRichert-NOAA and @AlysonStahl-NOAA

**Comment by edwardhartnett** [comment]
Now we have a few. More are needed...

I will close this issue and we will continue work under a new issue.
