### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by chriss1245** [NOAA-EMC/NCEPLIBS-grib_util#348]
I am wondering whether is possible to create a dockerfile for the installation of this library. Sorry I am not well versed with this and I am not able to get this running properly. If there was a docker file where it says how to install just from the begining I would use this library.

**Comment by edwardhartnett** [comment]
I would suggest you wait until after the imminent release of g2-4.0.0. In that release, we move the utilities to the g2 library.

The NCEPLIBS-grib_util repository (i.e. this repo) will then be deprecated. All users should instead upgrade their g2 library to get the latest versions of the utilities. (Aside from moving them to the g2 library, there have been no other changes, so if you are using the latest grib_utils release, you don't have to update immediately.)
