### ISSUE TITLE
Change directory names under sorc to remove file extensions

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-grib_util#37]
We have the following directories under sorc:

`cnvgrib.fd  copygb2.fd  copygb.fd  degrib2.fd  grb2index.fd  grbindex.fd  grib2grib.fd  tocgrib2.fd  tocgrib2super.fd  tocgrib.fd  wgrib.cd`

What's with the ".fd" and ".cd" for wgrib? Normally we don't have file extensions on our directory names...

**Comment by BoiVuong-NOAA** [comment]
Hi Ed.

Yes, You are right. The extension ".fd" is for Fortran folder and "cd" 
is for C folder for wgrib.   We are using the extension ".fd" and ".cd"  
for sources to make it same as in GFS package.

please see some sources in gfs v15 as an example:

/gpfs/dell1/nco/ops/nwprod/gfs.v15.3.3/sorc/*.fd

Thanks,

Boi

**Comment by edwardhartnett** [comment]
OK, let's leave that not-so-helpful convention in the past where it belongs. :-)
