### ISSUE TITLE
Add GNU Fortran 10 support

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/NCEPLIBS-grib_util#42]
@climbfuji reported that. grib_util cannot be built with gfortran-10.
It fails with the usual gfortran-10 error (rank mismatch between actual argument bla bla).

**Comment by aerorahul** [comment]
This is probably an issue with some of the other NCEPLIBS projects too.

**Comment by edwardhartnett** [comment]
This is actually a problem in every fortran library I am involved in outside of NCEPLIBS as well. ;-(

**Comment by kgerheiser** [comment]
We just have to add `-fallow-argument-mismatch`? Or is this something different?

**Comment by aerorahul** [comment]
But, can we also edit to this:
```
set(CMAKE_Fortran_FLAGS "${CMAKE_Fortran_FLAGS} -g")
```

To allow `FFLAGS` etc to be set from outside.

**Comment by edwardhartnett** [comment]
Setting flags is almost never the answer.

In fact, the fortran code should be cleaned up. But I've not tried it anywhere yet so I have no idea how hard it will be.

**Comment by kgerheiser** [comment]
I'm looking into it.

In this case I think we can fix the actual code. In other libraries we added the compiler flags.
