### ISSUE TITLE
Lots of duplicate code

### ISSUE THREAD

**Issue by kgerheiser** [NOAA-EMC/NCEPLIBS-grib_util#43]
Just some things I noticed:

wgrib2 is included with grib_util

`copygb2` has all the `polate` routines found in ip lib

`cnvgrib` contains `gds2gdt` which is also in the g2 library

**Comment by edwardhartnett** [comment]
Well wgrib2 is not actaully included, that's wgrib (i.e. for GRIB1 not GRIB2).

I have removed the extra polate routines in copygb2 - they were not being used by the code anyway.

That leaves gdt2gds.F90, which indeed appears in grib_util and also g2. Sigh.

What's annoying is that NCEPLIBS-g2 is already linked in. So why not just use it?

**Comment by edwardhartnett** [comment]
We are not going to mess with cnvgrib, because it's for GRIB1. Otherwise, we've done all the need to for this issue. I will close it.
