### ISSUE TITLE
Remove vector flags

### ISSUE THREAD

**Issue by kgerheiser** [NOAA-EMC/NCEPLIBS-grib_util#49]
Flags like `-axCORE-AVX2` are sprinkled throughout the code. This can cause problems on heterogenous platforms like Jet. 

Does grib_util need these flags? They've been removed from several other libraries.

**Comment by edwardhartnett** [comment]
I cannot find any such flags. Have they been removed or am I missing something?

**Comment by edwardhartnett** [comment]
But it is used a lot in the CMakeLists.txt files:

```
find . -name '*'|xargs grep -s axCORE
./tocgrib2/CMakeLists.txt:  set(CMAKE_Fortran_FLAGS "-g -axCORE-AVX2 ${CMAKE_Fortran_FLAGS}")
./tocgrib/CMakeLists.txt:  set(CMAKE_Fortran_FLAGS "-g -assume noold_ldout_format -axCORE-AVX2 ${CMAKE_Fortran_FLAGS}")
./tocgrib2super/CMakeLists.txt:  set(CMAKE_Fortran_FLAGS "-g -assume noold_ldout_format -axCORE-AVX2 ${CMAKE_Fortran_FLAGS}")
./degrib2/CMakeLists.txt:  set(CMAKE_Fortran_FLAGS "-g -convert big_endian -axCORE-AVX2 -fpp ${CMAKE_Fortran_FLAGS}")
./grb2index/CMakeLists.txt:  set(CMAKE_Fortran_FLAGS "-g -convert big_endian -axCORE-AVX2 -fpp ${CMAKE_Fortran_FLAGS}")
./grbindex/CMakeLists.txt:      "-g -assume noold_ldout_format -convert big_endian -axCORE-AVX2 -fpp ${CMAKE_Fortran_FLAGS}")
./grib2grib/CMakeLists.txt:      "-g -i8 -r8 -assume noold_ldout_format -axCORE-AVX2 -fpp ${CMAKE_Fortran_FLAGS}")
```

**Comment by edwardhartnett** [comment]
@GeorgeVandenberghe-NOAA @Hang-Lei-NOAA @AlexanderRichert-NOAA what do you think about this issue? 

We can just take these out, as @kgerheiser advised. I believe this will make no difference in output, and the tests will confirm that, but the test coverage is not great right now.

**Comment by Hang-Lei-NOAA** [comment]
We can try this change to see if it works for all models.

**Comment by edwardhartnett** [comment]
OK, let's do the next release, then take them out. That will give us some testing time without them.

**Comment by edwardhartnett** [comment]
@AlexanderRichert-NOAA do you have any thoughts on this? I am planning on taking out these vector flags for the next release...

**Comment by AlexanderRichert-NOAA** [comment]
I think it makes sense to remove them, then we can always set flags through spack-stack (incl. by system).
