### ISSUE TITLE
copygb2 doesn't work on WCOSS2

### ISSUE THREAD

**Issue by kgerheiser** [NOAA-EMC/NCEPLIBS-grib_util#58]
@GuangPingLou-NOAA could you describe the issue you're having with copygb2 on WCOSS2?

**Comment by GuangPingLou-NOAA** [comment]
Please see output file on Cactus:
/lfs/h2/emc/ptmp/Guang.Ping.Lou/tracks_nvgm_00.out15
and search for copygb2. The error messages are:
---------------------------------------------------------------------------------------------
 /apps/ops/prod/libs/intel/19.1.3.304/grib_util/1.2.2/bin/copygb2 -g '0 6 0
0 0 0 0 0 360 181 0 0 90000000 000000000 48 -90000000 359000000 1000000
1000000 0'
/lfs/h2/emc/ptmp/Guang.Ping.Lou/tracker_nvgm_00.6402/ngx/xxxx/nvgmgribfile.2021082400
/lfs/h2/emc/ptmp/Guang.Ping.Lou/tracker_nvgm_00.6402/ngx/xxxx/nvgmixfile.2021082400
/lfs/h2/emc/ptmp/Guang.Ping.Lou/tracker_nvgm_00.6402/ngx/xxxx/nvgmgribfileLL.2021082400
warning: empty layer generated
warning: empty layer generated
warning: empty layer generated
----------------------------------------------------------------------------------------------

The intended data file was not generated. while wgrib2 works in replacing
copygb2, it was not allowed during the transition.
Thanks,
Guang Ping

**Comment by kgerheiser** [comment]
Ah, I know this error! The g2 that grib_util was built with was built with `jasper/2.0.16` which has a bug with intel compilers. Grib_util just needs to be re-built with g2/3.4.5.

**Comment by GuangPingLou-NOAA** [comment]
That is great!

**Comment by kgerheiser** [comment]
This is an issue with Jasper, and not grib_util. Closing the issue.
