### ISSUE TITLE
tocgrib2super fails with "GETGB2P: ERROR REQUEST NOT FOUND"

### ISSUE THREAD

**Issue by kgerheiser** [NOAA-EMC/NCEPLIBS-grib_util#60]
A user is reporting an error with tocgrib2super on WCOSS2.

The error message is `GETGB2P: ERROR REQUEST NOT FOUND` which comes from the g2 library here;

https://github.com/NOAA-EMC/NCEPLIBS-g2/blob/4e98ae8e10f8994d77365a4fa424faa684e83f84/src/getgb2p.f#L160

After calling `getgb2s` to search the index here:

https://github.com/NOAA-EMC/NCEPLIBS-g2/blob/develop/src/getgb2s.f

There's a loop in there that searches for the requested index, but it's not found and returns an error:

https://github.com/NOAA-EMC/NCEPLIBS-g2/blob/4e98ae8e10f8994d77365a4fa424faa684e83f84/src/getgb2s.f#L310

@BoiVuong-NOAA @Hang-Lei-NOAA any ideas?

I went back and checked the library kinds and any changes in the program, but everything seems fine. I'm guessing the problem comes from g2.

```
* . * . * . * . * . * . * . * . * . * . * . * . * . * . * . * . * . * . * . * .
     PROGRAM tocgrib2super HAS BEGUN. COMPILED 2010902.50     ORG: NP11
     STARTING DATE-TIME  SEP 28,2021  20:33:21.953  271  TUE   2459486


  filesize            0
 DESC=SUPER WMO HEADER
 WMOHEAD=LAPZ99 KWBP

*******************************************************************************
 Start new record no. =  1
 DESC=1 HOUR SFC DUST
 WMOHEAD=LAPB07 KWBP
 GRIB2 DISCIPLINE= -1
 Section 1= -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999
 PDT 4. 8 = 13 195 2 0 6 0 0 1 0 103 0 100 103 0 0 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999
 LUGI =            0
 LUGB =           11
 jrew (number of fields to skip) =            0
  SAGT            0           0           2
 GETGB2P: ERROR REQUEST NOT FOUND

*******************************************************************************
 Start new record no. =  2
 DESC=1 HOUR SFC DUST
 WMOHEAD=LAPB08 KWBP
 GRIB2 DISCIPLINE= -1
 Section 1= -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999
 PDT 4. 8 = 13 195 2 0 6 0 0 1 1 103 0 100 103 0 0 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999
 LUGI =            0
 LUGB =           11
 jrew (number of fields to skip) =            0
 GETGB2P: ERROR REQUEST NOT FOUND

*******************************************************************************
 Start new record no. =  3
 DESC=1 HOUR SFC DUST
 WMOHEAD=LAPB09 KWBP
 GRIB2 DISCIPLINE= -1
 Section 1= -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999
 PDT 4. 8 = 13 195 2 0 6 0 0 1 2 103 0 100 103 0 0 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999
 LUGI =            0
 LUGB =           11
 jrew (number of fields to skip) =            0
 GETGB2P: ERROR REQUEST NOT FOUND

*******************************************************************************
 Start new record no. =  4
 DESC=1 HOUR SFC DUST
 WMOHEAD=LAPB10 KWBP
 GRIB2 DISCIPLINE= -1
 Section 1= -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999
 PDT 4. 8 = 13 195 2 0 6 0 0 1 3 103 0 100 103 0 0 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999
 LUGI =            0
 LUGB =           11
 jrew (number of fields to skip) =            0
 GETGB2P: ERROR REQUEST NOT FOUND
...
...
...
```

**Comment by kgerheiser** [comment]
Tried v3.4.1 of g2 (along with the most recent 3.4.5) with no success.

Here's a reproducer: https://github.com/kgerheiser/tocgrib2super-test

Just have to set the location of `tocgrib2super` and run `./test_script.sh`. 

Seeing the same behavior on my desktop with Intel, and GNU just segfaults.

**Comment by Hang-Lei-NOAA** [comment]
It could be either the file has problem or calling GETGB2S has problems.

**Comment by BoiVuong-NOAA** [comment]
It could be the problem of writing to output file while running in 
multiple nodes.

**Comment by edwardhartnett** [comment]
Any progress on this issue?

The answer for this, and similar issues, is to write a fortran test program in g2 which calls the exact set of g2 calls being called by tocgrib2super, with the same parameters.

This should then reproduce the problem in the g2 directory, where it can be debugged and solved. The test remains to make sure the bug is not re-introduced at any time in the future...

**Comment by edwardhartnett** [comment]
Is this issue still active?

**Comment by Hang-Lei-NOAA** [comment]
This has been resolved.
Thanks,Just close the ticket.
