### ISSUE TITLE
copygb not working on Jet

### ISSUE THREAD

**Issue by GeorgeGayno-NOAA** [NOAA-EMC/NCEPLIBS-grib_util#66]
One of the ufs_utils consistency tests use `copygb` as follows:

- `/lfs4/HFIP/hfv3gfs/nwprod/hpc-stack/libs/intel-18.0.5.274/grib_util/1.2.2/bin/copygb -M '#1.57' -x seaice.5min.blend.bitmap seaice.5min.blend`

`copygb` should be replacing the bitmap (at land points) in file `seaice.5min.blend.bitmap` with the flag value of '1.57'. But the flag value is not geolocated correctly. North America is in the wrong location. 

This test also uses `copygb2`. But that step is working. My test does not use any other components of `grib_util`.

I recompiled `grib_util` and the `copygb` step is working correctly.  See:

- `/lfs4/HFIP/hfv3gfs/emc.nemspara/role.ufsutils/ufs_utils/grib_util/NCEPLIBS-grib_util`

**Comment by kgerheiser** [comment]
You re-compiled what version of grib_util? Develop? And using what version of g2? Could it be a g2 issue?

**Comment by GeorgeGayno-NOAA** [comment]
> You re-compiled what version of grib_util? Develop? And using what version of g2? Could it be a g2 issue?

I compiled 'develop' at 17c7c8e. The problem is with `copygb`, not `copygb2`. So I would not think it is a `g2` problem. 

See the `build.sh` script in `/lfs4/HFIP/hfv3gfs/emc.nemspara/role.ufsutils/ufs_utils/grib_util/NCEPLIBS-grib_util` to see how I compiled.

**Comment by kgerheiser** [comment]
Ah, I bet it's this commit that fixed it: https://github.com/NOAA-EMC/NCEPLIBS-grib_util/commit/2a4d0cf97859f4365c5a4793134f11376bf69d82

But the latest version 1.2.3 was never installed on Jet.

**Comment by edwardhartnett** [comment]
Has this been resolved?

**Comment by edwardhartnett** [comment]
I'm going to assume this has been resolved. If not, please reopen the issue.
