### ISSUE TITLE
Doxygen needs serious help in all the code files

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-grib_util#77]
We have the bare minimum of doxygenation in this code base. Every utility needs a complete documentation overhaul to clean up the doxygen to our usual standards.

If anyone wants to jump in and do one of the utilities, feel free. Eventually I will work my way around to each of these, so move quickly if you want to do one. ;-)

**Comment by Hang-Lei-NOAA** [comment]
OKAY, I will start to do it.
