### ISSUE TITLE
What do prlevel.f and prvtime.f do in src/degrib2?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-grib_util#84]
What do prlevel.f and prvtime.f do in src/degrib2?

We have these two codes, but they have no documentation.

What do they do? Who wrote them? Any ideas?

**Comment by edwardhartnett** [comment]
@BoiVuong-NOAA ?

**Comment by BoiVuong-NOAA** [comment]
These two prelev.f and prvtime.f are decoder in degrib2.

**Comment by edwardhartnett** [comment]
Who wrote prlevel.f and prvtime.f? Was there some reason these codes are not documented?

If there are both decoders what is the difference? Why is one called level and the other time? Any reason?

**Comment by BoiVuong-NOAA** [comment]
Steve wrote these codes.  I do not know why there is no document for these codes.
The level is for level in fields in grib2 file and time is for forecast time in grib2 file.

**Comment by edwardhartnett** [comment]
Did Steve write degrib2.f as well?

**Comment by BoiVuong-NOAA** [comment]
Yes

**Comment by edwardhartnett** [comment]
This is all documented now...
